AzureStorage/Models/ErrorViewModel.cs
namespace AzureStorage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AzureStorage/Models/Instance.cs
using System.ComponentModel.DataAnnotations;

namespace AzureStorage.Models
{
    public class Instance
    {
        const double VerySmallCharge = 0.02;
        const double SmallCharge = 0.08;
        const double MediumCharge = 0.16;
        const double LargeCharge = 0.32;
        const double VeryLargeCharge = 0.64;
        const double A6Charge = 0.90;
        const double A7Charge = 1.80;

        public static String[] InstanceSizes
        {
            get
            {
                return new String[] { "Very Small", "Small", "Medium", "Large", "Very Large", "A6", "A7" };
            }
        }
        public string InstanceSize { get; set; }
        [Range(2, int.MaxValue, ErrorMessage = "A cloud service must have at least 2 instances according to the Azure Compute SLA. Please enter a value greater than 2")]
        public int NoOfInsta { get; set; }
        public double Charge
        {
            get
            {
                double charge = 0;
                if (DateTime.IsLeapYear(DateTime.Now.Year))
                {
                    if (InstanceSize == "Very Small")
                    {
                        charge = NoOfInsta * VerySmallCharge * 24 * 366;
                    }
                    else if (InstanceSize == "Small")
                    {
                        charge = NoOfInsta * SmallCharge * 24 * 366;
                    }
                    else if (InstanceSize == "Medium")
                    {
                        charge = NoOfInsta * MediumCharge * 24 * 366;
                    }
                    else if (InstanceSize == "Large")
                    {
                        charge = NoOfInsta * LargeCharge * 24 * 366;
                    }
                    else if (InstanceSize == "Very Large")
                    {
                        charge = NoOfInsta * VeryLargeCharge * 24 * 366;
                    }
                    else if (InstanceSize == "A6")
                    {
                        charge = NoOfInsta * A6Charge * 24 * 366;
                    }
                    else if (InstanceSize == "A7")
                    {
                        charge = NoOfInsta * A7Charge * 24 * 366;
                    }
                }
                else
                {
                    if (InstanceSize == "Very Small")
                    {
                        charge = NoOfInsta * VerySmallCharge * 24 * 365;
                    }
                    else if (InstanceSize == "Small")
                    {
                        charge = NoOfInsta * SmallCharge * 24 * 365;
                    }
                    else if (InstanceSize == "Medium")
                    {
                        charge = NoOfInsta * MediumCharge * 24 * 365;
                    }
                    else if (InstanceSize == "Large")
                    {
                        charge = NoOfInsta * LargeCharge * 24 * 365;
                    }
                    else if (InstanceSize == "Very Large")
                    {
                        charge = NoOfInsta * VeryLargeCharge * 24 * 365;
                    }
                    else if (InstanceSize == "A6")
                    {
                        charge = NoOfInsta * A6Charge * 24 * 365;
                    }
                    else if (InstanceSize == "A7")
                    {
                        charge = NoOfInsta * A7Charge * 24 * 365;

                    }
                }
                return Math.Round(charge, 2);
            }
        }
    }
}

AzureStorage/Models/Storage.cs
namespace AzureStorage.Models
{
    public class Storage
    {
        public int GigaBytes { get; set; }
        public bool GeoRedundant { get; set; }
        public double StorageCost
        {
            get
            {
                double MoreThanTB = GigaBytes - 1000;   // Number of Gigabytes more than 1TB
                double charge = 0;
                if (GeoRedundant)
                {
                    if (GigaBytes <= 1000)
                    {
                        charge = GigaBytes * 0.125;
                    }
                    else
                    {
                        charge = 1000 * 0.125 + GigaBytes * 0.11;
                    }
                }
                else    // if locally redundant
                {
                    if (GigaBytes <= 1000)
                    {
                        charge = GigaBytes * 0.093;
                    }
                    else
                    {
                        charge = 1000 * 0.093 + MoreThanTB * 0.083;
                    }
                }
                return Math.Round(charge,2);    // round the result to 2 decimal places
            }
        }
    }
}

AzureStorage/Controllers/HomeController.cs
using AzureStorage.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AzureStorage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AzureStorage/Controllers/InstanceController.cs
using AzureStorage.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AzureStorage.Controllers
{
    public class InstanceController : Controller
    {
        // GET: InstanceController/Create
        public ActionResult CalculateInstance()
        {
            ViewBag.InstanceSize = new SelectList(Instance.InstanceSizes);
            return View(new Instance { InstanceSize = "Small" });
        }

        // POST: InstanceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CalculateInstance(Instance instance)
        {
            ViewBag.InstanceSize = new SelectList(Instance.InstanceSizes);
            ViewBag.Charge = instance.Charge;
            return View(instance);
        }
    }
}

AzureStorage/Controllers/StorageController.cs
using AzureStorage.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AzureStorage.Controllers
{
    public class StorageController : Controller
    {
        // GET: StorageController/Create
        public ActionResult Calculate()
        {
            return View();
        }

        // POST: StorageController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Calculate(Storage storage)
        {
            ViewBag.StorageCost = storage.StorageCost;
            return View(storage);
        }
    }
}

AzureStorage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Azure Storage and Instance Calculator</h1>
    <h4>Here you can calculate the predicted monthly cost for your Azure storage based on the storage amount you plan to use and calculate the predicted yearly cost of running Azure instance.</h4>
    <br />
    <p>You can refer to the steps below on how to use the storage calculator.</p>
    <ol class="steps">
        <li>Input the number of Gigabytes you plan to use on Azure per month.</li>
        <li>Tick the box if it is Geographically redundant.</li>
        <li>Click the <b>Calculate</b> button to get your predicted monthly cost.</li>
    </ol>
    <br />
    <p>You can refer to the steps below on how to use the instance calculator.</p>
    <ol class="steps">
        <li>Select the instance size.</li>
        <li>Input the number of instances.</li>
        <li>Click the <b>Calculate</b> button to get your predicted yearly cost.</li>
    </ol>
</div>

AzureStorage/Views/Instance/CalculateInstance.cshtml
@model AzureStorage.Models.Instance

@{
    ViewData["Title"] = "CalculateInstance";
}

<h1>Calculate Instance</h1>

<h4>Instance</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CalculateInstance">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InstanceSize" class="control-label"></label>
                @Html.DropDownList("InstanceSize")
                <span asp-validation-for="InstanceSize" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="NoOfInsta" class="control-label"></label>
                <input asp-for="NoOfInsta" class="form-control" />
                <span asp-validation-for="NoOfInsta" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Calculate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <h4>Predicted yearly instance cost ($): @ViewBag.Charge</h4>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AzureStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AzureStorage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AzureStorage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AzureStorage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Storage" asp-action="Calculate">Calculate Storage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instance" asp-action="CalculateInstance">Calculate Instance</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AzureStorage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AzureStorage/Views/Storage/Calculate.cshtml
@model AzureStorage.Models.Storage

@{
    ViewData["Title"] = "Calculate Storage";
}

<h1>Calculate Storage</h1>

<h4>Storage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Calculate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GigaBytes" class="control-label"></label>
                <input asp-for="GigaBytes" class="form-control" />
                <span asp-validation-for="GigaBytes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GeoRedundant" /> @Html.DisplayNameFor(model => model.GeoRedundant)
                </label>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Calculate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <h4>Predicted monthly storage cost ($): @ViewBag.StorageCost</h4>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}